Cat 21
VicDoom/cat-pairs pull request #12
Opened 2024-03-14 16:49 UTC by VoskresenskayaM

### верстка страницы профайла

2024-03-15 14:52 UTC, grozzzny requested changes
В целом все неплохо. Однако по задаче нужно реализовать API для полноценной проверки в действии. Заодно подтянуть готовые input и button. 

Валидация - это хорошо. Но данная задача висит на мне. Буду реализовывать после написания участниками проекта всех форм. Так как мы используем antd, то лучше максимально использовать функционал данной библиотеки, меньше будет конфликтов в реализации данного подхода

2024-03-15 14:52 UTC, grozzzny commented on packages/client/package.json
> +    "react-hook-form": "^7.51.0",
У нас была договоренность фиксировать версии. Поэтому этот символ не нужен "^"
 Получится так: "react-hook-form": "7.51.0",

2024-03-15 14:52 UTC, grozzzny commented on packages/client/src/components/profile-avatar/profile-avatar.css
> +.profile-avatar__container {
Мне нравится как придумываешь названия классов

2024-03-15 14:52 UTC, grozzzny commented on packages/client/src/components/profile-avatar/profile-avatar.tsx
> +    //запрос на сервер '@/../../public/avatar.png'
В рамках задачи, должна быть реализация API. 
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/f9411a9d-90a9-4439-a223-445f6dd27e34)

2024-03-15 14:52 UTC, grozzzny commented on packages/client/src/components/profile-popup/profile-popup.css
> +  background-color: #565a5d;
Повторяющие цвета рекомендуются использовать в переменных

2024-03-15 14:52 UTC, grozzzny commented on packages/client/src/components/profile-popup/profile-popup.css
> +.popup__form-button {
Можно будет подтянуть компонент с кнопкой. Есть темная и светлая тема. Пока она находится в ветке CAT-18.

2024-03-15 14:52 UTC, grozzzny commented on packages/client/src/components/profile-avatar/profile-avatar.css
> +.profile-avatar__container {
Ширина темной подложки больше, чем на макете. 
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/edb2e437-fca9-4c68-b458-4b51bdf4dff9)

В макете
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/559e129b-a75e-4eed-b92e-b33aeecd923a)

Не принципиально.

2024-03-15 14:52 UTC, grozzzny commented on packages/client/src/components/profile-form/profile-form.tsx
> +    <form onSubmit={handleSubmit(submit)} className='profile-form'>
У нас используется библиотека antd. В ней есть компонент формы. Лучше задействовать его, так как предстоит унифицировать работу формы и валидацию по всему проекту. 
https://ant.design/components/form

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/e89c7ae0-29c4-4a25-ad78-3f7bd435421c)

По идее это не большие правки. 
```
<Form>
<Form.Item label="Checkbox" name="disabled" valuePropName="checked">
          Компонент инпута
        </Form.Item>
```

2024-03-15 14:52 UTC, grozzzny commented on packages/client/src/components/profile-form/profile-form.tsx
> +          <input
Инпуты тоже нужно задействовать наши. Они уже должны быть в dev

<img width="220" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/5270d972-afbc-4a81-8703-2bb5270bc276">

2024-03-15 14:52 UTC, grozzzny commented on packages/client/src/components/profile-popup/profile-popup.css
> +  background-color: var(--base-dark);
Отлично!!) что используется var

2024-03-16 15:22 UTC, VicDoom commented on packages/client/package.json
> +    "react-hook-form": "7.51.0",
ни разу не использовал данную библиотеку, но можно попробовать

2024-03-16 15:23 UTC, VicDoom commented on packages/client/src/components/profile-form/profile-form.tsx
> +      firstName: currentUser.firstName,
давай defaultUser: {...currentUser}

2024-03-16 15:26 UTC, VicDoom commented on packages/client/src/index.css
> +  --base-red: #ee2d39;
цвета повторяются, только red новый + перенесли все основные цвета в отдельный файл (подтяни потом dev)

2024-03-16 15:27 UTC, VicDoom commented on packages/client/src/pages/profile-page/profile-page.css
> +  display: flex;
пожалуйста, обрати внимание на компонент Flex из antd, стили про флексы очень часто повторяются:

https://ant.design/components/flex

2024-03-16 15:28 UTC, VicDoom commented on packages/client/src/routes.tsx
> +    path: '/new-password',
хорошо, у нас новая страница, но давай назовем change-password

2024-03-17 22:46 UTC, VicDoom commented on packages/client/package.json
> +    "react-hook-form": "7.51.0",
из последней встречи выяснили, что не используем данную библиотеку, удаляем

2024-03-17 22:47 UTC, VicDoom commented on packages/client/src/api/user.ts
> +    return await fetch(`${YANDEX_API_HOST}/user/password`, {
обязательно: чуть позже будет влита CAT-15, там есть fetchHelper, добавь его, пожалуйста

2024-03-17 22:49 UTC, VicDoom commented on packages/client/src/components/profile-form/profile-form.tsx
> +import { SubmitHandler, useForm } from 'react-hook-form';
здесь и далее по коду можно удалить

2024-03-17 22:54 UTC, VicDoom commented on packages/client/src/components/profile-popup/profile-popup.tsx
> +      const formData = new FormData();
эту логику с созданием FormData можно перенести в контроллер (некритично)

2024-03-17 22:55 UTC, VicDoom commented on packages/client/src/components/profile-popup/profile-popup.tsx
> +    //авторизация
авторизация будет вместе с CAT-15, после того, как к себе подольешь - удали комментарии (здесь и далее по коду)

2024-03-20 07:55 UTC, grozzzny approved these changes
Была проделанная большая работа!

2024-03-20 09:03 UTC, VicDoom commented on packages/client/src/api/user.ts
>    static async changeAvatar(data: FormData) {
записал, чуть позже добавлю возможность переопределять Content-Type в headers, с целью экономии времени оставляем это решение

2024-03-20 09:17 UTC, VicDoom approved these changes

2024-03-20 09:36 UTC, merged