add(CAT-19): leaderboard page
VicDoom/cat-pairs pull request #20
Opened 2024-03-20 12:56 UTC by nsinetskiy

### Какую задачу решаем
Сверстать страницу лидерборда
Добавлен роут для лидерборда, при переходе авторизованного пользователя на этот экран отображается список моковых рекордов.
Лидерборд представляет собой список рекордов пользователей игры.

### Скриншот
![image](https://github.com/VicDoom/cat-pairs/assets/10059268/56d9d50e-3ac6-4076-b5bd-1ae792bd057f)

2024-03-20 16:57 UTC, VoskresenskayaM approved these changes
отлично

2024-03-20 16:57 UTC, VoskresenskayaM commented on packages/client/src/components/leader-card/leader-card.tsx
> +import './leader-card.css';
отлично, что используешь Flex из ant

2024-03-21 14:58 UTC, grozzzny requested changes
Все комментарии рекомендательного и информационного характера за исключением с аватарками. Необходимо либо убрать отображение url, либо использовать тег img

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/8068a210-9136-4808-8ef3-294e499053ad)

<img width="815" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/b3a17c2a-f47a-460a-8296-8136935825a4">

2024-03-21 14:58 UTC, grozzzny commented on packages/client/public/crown.svg
Отлично что иконка лежит в директории public и формат ее svg

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leader-card/leader-card.css
> +  width: 478px;
Фиксированные размеры пожалуй подойдут для этого проекта, но в реальных проектах лучше всегда использовать адаптив на все виды экранов.

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leader-card/leader-card.css
> +.leader-card__icon {
Отлично применяешь BEM.

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leader-card/leader-card.tsx
> +        {avatar}
Здесь не очень правильная реализация. Обычно для использования картинок используют тег img с атрибутом alt. Также если нет аватарки у пользователя, то вставляют картинку заглушку. 

{avatar} - здесь выведется url? Судя по логике да. Зачем?

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/ee2eed1b-ef2d-46f2-a4be-5b1b6180923e)

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leader-card/leader-card.tsx
> +  avatar: string;
avatar?: string; - здесь лучше поставить вопросительный знак. Логику объяснил чуть ниже

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leader-card/leader-card.css
> +.leader-card__avatar {
Очень полезное и безопасное свойство для использования картинок в случае если не будет предварительной обработки картинок. Советую его использовать. Картинка в данном случае, будет вписываться в заданные размеры. Но лучше конечно использовать заранее подготовленные картинки с сервера
.leader-card__avatar img {
    object-fit: cover;
}

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leaders-table/leaders-table.css
> +  width: 978px;
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/c754e3a9-5943-48e7-a4fe-faaf3f0cf566)

Практически у всех фреймворков есть адаптив. Была бы хорошая практика всегда помнить об этом, чтобы верстать один раз и не возвращаться к этому вопросу. Наша текущая задача не предусматривает это, поэтому это как рекомендация на будущее для реальных проектов

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/926123af-b0a9-4173-8f9a-901a4daec800)

https://ant.design/components/grid

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leader-card/leader-card.tsx
> +export const LeaderCard = ({
В реакте можно передать дженерик для указания типов свойств (props), передаваемых в компонент React.FC<Props>,  Такой подход считается более правильный, но твое решение тоже имеет место быть

const ExampleReactComponent: React.FC<ExampleReactComponentProps> = (props) => {

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leaders-table/leaders-table.tsx
> +          key={item.position}
Хорошо, что используешь ключи

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/components/leaders-table/leaders-table.tsx
> +  avatar: string;
avatar?: string; - уже писал об этом выше

2024-03-21 14:58 UTC, grozzzny commented on packages/client/src/helpers/constants/leaderboard.ts
> +export const LEADERS_LIST = [
Даже для временных решений, всегда лучше для самопроверки и использовать возможности typescript с его типами. Таким образом ошибок будет гораздо меньше. 

import { Leader } from '@/components/leaders-table/leaders-table';

export const LEADERS_LIST: Leader[] = [

2024-03-23 13:19 UTC, nsinetskiy commented on packages/client/src/components/leader-card/leader-card.tsx
> +        {avatar}
Поправил. Действительно странно. Видимо, как-то случайно копипастнул, не заметил и не проверил.

2024-03-23 13:20 UTC, nsinetskiy commented on packages/client/src/components/leader-card/leader-card.tsx
> +  avatar: string;
Добавил.

2024-03-23 13:20 UTC, nsinetskiy commented on packages/client/src/components/leader-card/leader-card.css
> +.leader-card__avatar {
Спасибо, добавил.

2024-03-23 13:22 UTC, nsinetskiy commented on packages/client/src/components/leaders-table/leaders-table.css
> +  width: 978px;
Спасибо за рекомендацию. Пока оставил как есть. Там карточки добавляются из массива map'ом, поэтому не уверен, что данный подход с колонками здесь подойдёт. Или надо ещё подумать, получше поразбираться с библиотекой.

2024-03-23 13:23 UTC, nsinetskiy commented on packages/client/src/components/leader-card/leader-card.tsx
> +export const LeaderCard = ({
Сделал.

2024-03-23 13:23 UTC, nsinetskiy commented on packages/client/src/helpers/constants/leaderboard.ts
> +export const LEADERS_LIST = [
Типизацию добавил.

2024-03-23 13:25 UTC, nsinetskiy commented on packages/client/src/components/leader-card/leader-card.css
> +  width: 478px;
Насчёт адаптива полностью согласен, но пока оставил так, чтобы время сейчас не тратить, так как адаптив у нас пока опционален.

2024-03-23 13:52 UTC, grozzzny approved these changes
Отлично.

2024-03-23 16:05 UTC, merged