CAT-17 [Валидация на все формы]
VicDoom/cat-pairs pull request #22
Opened 2024-03-20 16:30 UTC by grozzzny

### Какую задачу решаем
Должны быть следующие проверки (добавлять дополнительные правила валидации не нужно): 

- first_name, second_name — латиница или кириллица, первая буква должна быть заглавной, без пробелов и без цифр, нет спецсимволов (допустим только дефис). 

- login — от 3 до 20 символов, латиница, может содержать цифры, но не состоять из них, без пробелов, без спецсимволов (допустимы дефис и нижнее подчёркивание). 

- email — латиница, может включать цифры и спецсимволы вроде дефиса, обязательно должна быть «собака» (@) и точка после неё, но перед точкой обязательно должны быть буквы. 

- password — от 8 до 40 символов, обязательно хотя бы одна заглавная буква и цифра. 

- phone — от 10 до 15 символов, состоит из цифр, может начинаться с плюса.

Валидация должна работать по focus/blur событиям и второй раз проверяться при нажатии на submit. У валидации должен быть единый механизм: 

- авторизация, 

- регистрация, 

- настройки пользователя.

### Скриншоты/видяшка (если есть)
<img width="599" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/e7287239-d880-46a9-87c2-558af27eeda0">
<img width="604" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/2259763a-d1db-4112-b898-04230d36e811">
<img width="859" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/b1bc86c2-9e15-4b62-9b94-2329a11e6ca4">

### TBD (если есть)
Отрефакторил страницу profile, компоненты Input и ButtonExit

2024-03-20 16:49 UTC, VoskresenskayaM approved these changes
проделана большая работа

2024-03-20 16:49 UTC, VoskresenskayaM commented on packages/client/src/components/profile-form/profile-form.css
> +
хорошо, что учтены все состояния инпута

2024-03-20 16:49 UTC, VoskresenskayaM commented on packages/client/src/components/profile-form/profile-form.tsx
>        </div>
отлично, все формы в проекте унифицированы

2024-03-20 19:49 UTC, VicDoom commented
Все хорошо, но есть пара обязательных моментов:
1. Нужно добавить валидацию на страницу смены пароля
2. Если react-hook-form больше не используется в проекте, то нужно удалить его из зависимостей (и в lock-файле)

2024-03-20 23:41 UTC, grozzzny commented
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/aa0486c0-8888-495c-ac29-77c9edeee9ba)

2024-03-21 08:16 UTC, VicDoom approved these changes

2024-03-22 06:36 UTC, IvanPeleshok requested changes
Добрый день!

Отлично потрудились

Есть пара замечаний, которые можно бы было поправить, но не сказал бы, что они являются на данный момент критическими

Предлагаю с ними ознакомиться и самим решить, что править, а что оставить как есть

Хорошего дня :)

2024-03-22 06:36 UTC, IvanPeleshok commented on packages/client/src/components/profile-form/profile-form.css
> +  text-align: end !important;
!important рекомендую использовать только при особой необходимости
Чаще всего поднимают приоритет правил с помощью каскадности стилей https://wp-kama.ru/note/css-prioritety-kaskadnost

2024-03-22 06:36 UTC, IvanPeleshok commented on packages/client/src/components/input/input.tsx
> +    return <AntInput className='input' {...restProps} />;
По ощущениям, было бы проще реализовать в отдельных модулях данные поля, чтобы было проще манипулировать ими и поддерживать

2024-03-22 06:36 UTC, IvanPeleshok commented on packages/client/src/helpers/validators.ts
Прекрасно, что сами реализовали валидацию

Предложил бы вам посмотреть на уже готовые решения, которые протестированы и достаточно просто использовать Formik + yup https://formik.org/docs/guides/validation#validationschema

2024-03-22 06:36 UTC, IvanPeleshok commented on packages/client/src/pages/profile-page/profile-page.tsx
> +            onClick={() => navigate('../change-password')}>
Инлайн-колбеки сложно читать и масштабировать

Предагаю вынести в отдельную функцию
```
const Component = () => {
  const handleCalick = () => { ... }
  
  return <div onClick={handleClick} />

2024-03-22 08:49 UTC, grozzzny commented on packages/client/src/components/input/input.tsx
> +    return <AntInput className='input' {...restProps} />;
Кто то из членов команды добавил класс во все инпуты. Я не вдавался в подробности зачем он это сделал. Просто сохранил при рефакторинге.

2024-03-22 08:52 UTC, grozzzny commented on packages/client/src/components/profile-form/profile-form.css
> +  text-align: end !important;
Здесь каскадность не подойдет, так как это библиотека antd и для нее нужно использовать ConfigProvider (Провайдер стилей), но так как эта задача по верстке была не на мне, а на другом участнике, который использовал подход important в других своих css файлах, то я сохранил данную логику.

2024-03-22 08:56 UTC, grozzzny commented on packages/client/src/helpers/validators.ts
Хорошо! Обязательно посмотрю

2024-03-22 08:57 UTC, grozzzny commented on packages/client/src/pages/profile-page/profile-page.tsx
> +            onClick={() => navigate('../change-password')}>
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/cd0f0298-4d56-4a18-a858-5b25001a08a8)
Тут так было. Я всего лишь добавлял валидацию. Форму не я верстал и не я добавлял логику.

2024-03-22 09:01 UTC, merged