CAT-31 | [Авторизация должна проверяться через отдельно написанный Hook или HOC]
VicDoom/cat-pairs pull request #27
Opened 2024-03-24 21:54 UTC by VicDoom

### Какую задачу решаем

1. Добавлены хук withAuth и HOC withAuthRouteHOC
2. В страницах, в которых нужна проверка авторизации, поправлены импорты.

### TBD (если есть)

1. Бага с двойным запросом api/v2/auth/user не является багом - в dev-режиме StrictMode рендерит приложение App дважды (https://stackoverflow.com/questions/60618844/react-hooks-useeffect-is-called-twice-even-if-an-empty-array-is-used-as-an-ar)

2024-03-25 11:20 UTC, grozzzny requested changes
В целом использование Hook и HOC верное. Была проделана хорошая работа. Однако есть баг, который желательно подправить. Вот мои тестовые данные для входа: 
Login: ttt
Password: qwertyQWERTY123

Создав пользователя через API, не получается войти. Пишет что пользователь уже в системе. Закрытые страницы после ввода пароля и логина доступны, но не происходит переадресация. Таким образом есть ошибки в логике. 

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/2e9fec88-9c2e-4b4a-9173-5e9fc1622091)

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/58e34bcf-46d6-4c2a-8a04-6afd617e26bf)

2024-03-25 11:20 UTC, grozzzny commented on packages/client/src/components/page-wrapper/page-wrapper.tsx
> +import { PageWrapperProps } from '@/helpers/types';
PageWrapperProps Используется только в page-wrapper.tsx. Разве имеет смысл делать отдельным импортом? По такой логике нужно для всех компонентов все типы пропсов перетащить в @/helpers/types. 

В общем на усмотрение автора. (Ничего критичного..)

2024-03-25 11:20 UTC, grozzzny commented on packages/client/src/helpers/hooks/withAuthRouteHOC.tsx
> +const authProviderStyles = {
Было бы лучше сделать spin отдельным компонентом. Стили реализовать также, как все существующие компоненты. Не критично

2024-03-25 11:20 UTC, grozzzny commented on packages/client/src/helpers/hooks/withAuthRouteHOC.tsx
> +    return <WrappedRoute {...props} />;
В данном случае, TypeScript ожидает, что T будет иметь тип, который расширяет IntrinsicAttributes

<img width="878" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/27f78bd5-6f64-497b-934f-58b5f4fbcbb0">

2024-03-25 11:20 UTC, grozzzny commented on packages/client/src/helpers/hooks/withAuthRouteHOC.tsx
> +    return <WrappedRoute {...props} />;
чтобы исправить, нужно тип T унаследовать от JSX.IntrinsicAttributes

2024-03-25 11:20 UTC, grozzzny commented on packages/client/src/helpers/hooks/withAuthRouteHOC.tsx
> +  const ComponentWithAuth = (props: T) => {
Здесь можно использовать более короткую запись:
return (props: T) => {
(Просто комментарий..)

2024-03-25 11:20 UTC, grozzzny commented on packages/client/src/providers/auth-provider.tsx
> +    AuthService.getUser().then(isOk => (isOk ? handleAuth() : stopLoading()));
при размонтировании компонента (componentWillUnmount) желательно отменить асинхронные запросы
```
useEffect(() => {
     AuthService.getUser().then(isOk => (isOk ? handleAuth() : stopLoading()));
    return () => {
      AuthService.cancel();
    };
  }, []);
```

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/c1792c6f-735d-45ea-ba98-0045b15815be)

2024-03-25 11:20 UTC, grozzzny commented on packages/client/src/providers/auth-provider.tsx
> +    AuthService.getUser().then(isOk => (isOk ? handleAuth() : stopLoading()));
5 спринт. тема "Хуки – что за модное слово"

2024-03-25 11:26 UTC, grozzzny commented on packages/client/src/providers/auth-provider.tsx
> +    AuthService.getUser().then(isOk => (isOk ? handleAuth() : stopLoading()));
"(то есть на componentWillUnmount) — в ней стоит остановить асинхронные операции"

2024-03-25 13:30 UTC, VicDoom commented on packages/client/src/components/page-wrapper/page-wrapper.tsx
> +import { PageWrapperProps } from '@/helpers/types';
вернул обратно в page-wrapper

2024-03-25 13:32 UTC, VicDoom commented on packages/client/src/helpers/hooks/withAuthRouteHOC.tsx
> +    return <WrappedRoute {...props} />;
у меня на текущий момент нет этой ошибки, может, баг в ide

2024-03-25 13:34 UTC, VicDoom commented on packages/client/src/providers/auth-provider.tsx
> +    AuthService.getUser().then(isOk => (isOk ? handleAuth() : stopLoading()));
добавил отмену запроса - но закомментировал (см TODO в auth-provider), тк сейчас в StrictMode приложение рендерится дважды, и запрос в первый раз отменяется всегда, и приложение падает

2024-03-25 14:25 UTC, grozzzny approved these changes
Баг исправлен. Хорошо!

2024-03-25 23:41 UTC, nsinetskiy commented on packages/client/src/helpers/hooks/withAuthRouteHOC.tsx
> +    return <WrappedRoute {...props} />;
У меня такая ошибка тоже есть (Visual Studio Code). Наследование T от JSX.IntrinsicAttributes решает проблему - `export function withAuthRouteHOC<T extends JSX.IntrinsicAttributes>(WrappedRoute: React.ComponentType<T>) {`.

2024-03-26 00:03 UTC, nsinetskiy requested changes
Всё хорошо, нужно только поправить ошибку TypeScript в withAuthRouteHOC.

2024-03-26 10:13 UTC, VicDoom commented on packages/client/src/helpers/hooks/withAuthRouteHOC.tsx
> +    return <WrappedRoute {...props} />;
добавил расширение типа T "вслепую", так и не удалось как-то заставить линтер подсветить ошибку

2024-03-26 10:49 UTC, nsinetskiy commented on packages/client/src/helpers/hooks/withAuthRouteHOC.tsx
> +    return <WrappedRoute {...props} />;
Спасибо, ошибка ушла.

2024-03-26 10:50 UTC, nsinetskiy approved these changes

2024-03-26 12:41 UTC, merged