Cat 33[Добавить Redux хранилище]
VicDoom/cat-pairs pull request #28
Opened 2024-03-25 13:15 UTC by VoskresenskayaM

### Какую задачу решаем
Подключение Redax хранилища, хранение данных пользователя, хранение данных о теме

### Скриншоты/видяшка (если есть)
![image](https://github.com/VicDoom/cat-pairs/assets/57997785/ec3162c1-66ab-4d38-b60c-7f5b4443a7de)
данные о пользователе подгружаются из store 

![image](https://github.com/VicDoom/cat-pairs/assets/57997785/c09bfd54-78d1-4709-b108-b4b42339f3db)
реализована смена данных пользователя, при успешном обновлении появляется уведомление

https://skr.sh/vOvz7Drr061
если запрос на изменение данных пользователя проходит с ошибкой, появляется уведомление об ошибке

https://skr.sh/vOv54WYvcPP
добавлен запрос для выхода из игры

https://skr.sh/vOv4bOz4Yfz
добавлена возможность менять тему

### TBD (если есть)
доработать компоненты и страницы для темной темы

2024-03-25 21:41 UTC, VicDoom commented on packages/client/src/main.tsx
> +    <Provider store={store}>
лучше перенести  Provider в App.tsx к остальным провайдерам

(необязательно)

2024-03-25 21:41 UTC, VicDoom commented on packages/client/src/pages/main-page/main-page.tsx
> +    dispatch(fetchGetCurrentUser());
сейчас в апи улетает 2 запроса для получения данных пользователя, в main-page.tsx и в auth-provider.tsx, это совсем неоптимально, давай сделаем так, чтобы информация о пользователе сохранялась в store в auth-provider.tsx

если пользователь авторизован - вытаскиваем данные и сразу же сохраняем в store, до перехода в main-page

(обязательно)

2024-03-25 21:42 UTC, VicDoom commented on packages/client/src/pages/main-page/main-page.tsx
> +    console.log(theme);
информацию о теме нужно скрыть от пользователя в консоли

(обязательно)

2024-03-25 21:42 UTC, VicDoom commented on packages/client/src/store/userSlice.ts
> +  isPopupOpen: false,
хранить в state состояние модалок (закрыто/открыто) точно не надо, достаточно передавать параметры open и setClose

(обязательно)

2024-03-25 21:49 UTC, VicDoom commented on packages/client/src/store/userSlice.ts
> +  status: null,
вроде как status и loading используются только в самих редьюсерах, но в самих компонентах их нет, они точно нужны в store?

2024-03-26 00:26 UTC, grozzzny approved these changes
Переключение тем работает. Хорошо! Также видно что был рефакторинг. Отлично. Есть замечания от Никиты, их желательно поправить.

2024-03-26 00:26 UTC, grozzzny commented on packages/client/package.json
> +    "@reduxjs/toolkit": "2.2.2",
Отлично что фиксируешь версии

2024-03-26 00:26 UTC, grozzzny commented on packages/client/src/store/userSlice.ts
> +import { ProfileFieldType, User } from '../helpers/types/user';
'@/helpers/types'; Можно сократить путь. (Реком.)

2024-03-26 00:26 UTC, grozzzny commented on packages/client/src/store/index.ts
> +export type AppThunk<ReturnType = void> = ThunkAction<
Данный тип нигде не используется

2024-03-27 10:48 UTC, VicDoom approved these changes
Все отлично!

2024-03-27 19:09 UTC, IvanPeleshok requested changes
Прекрасно поработали, нравится

Есть небольшие замечания, которые предлагаю поправить

Хорошего дня :)

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/components/exit-button/exit-button.tsx
> +    } else {
С учётом того, что используется return в if, то в else нет необходимости

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/components/profile-form/profile-form.tsx
> +      });
Предлагаю воспользоваться return, тогда можно будет избавиться от else, что упростит понимани и плоскость логики

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/pages/main-page/main-page.tsx
> +                onClick={() => dispatch(setThemeDark())}
Возможно имеет смысл создать один reducer, который будет принимать в аргументы тему?

Таким образом, мы сократим количества код и его поддержку

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/providers/auth-provider.tsx
> +            return;
Если попадём сюда, то не отработает stopLoading

Так и предполагалось?

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/providers/auth-provider.tsx
> +      UserService.getCurrentUser({ signal: abortController.signal }).then(
Предлагаю воспользоваться async / await + try / catch
Такой код проще дебажить и читать
```
try {
  const response = await UserService.getCurrentUser({ signal: abortController.signal })
  if (response?.isOk && response.user) {
    dispatch(setCurrentUser(res.user));
  }
} catch (ex) {
  handleError(ex)
}
```

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/services/user.ts
> +        return { isOk: true, user: user };
Аналогично, нет смысла в else (и в других аналогичных кейсах)
Только усложняем чтении ветвением логики

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/store/index.ts
> +/*export type AppThunk<ReturnType = void> = ThunkAction<
Если не используется, то предлагаю удалить, либо оставить осмысленный коммент для чего

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/store/userSlice.ts
> +export const fetchGetCurrentUser = createAsyncThunk<
Здорово, что используете createAsyncThunk

2024-03-27 19:09 UTC, IvanPeleshok commented on packages/client/src/store/userSlice.ts
> +  } else return result?.error && rejectWithValue(result?.error);
Аналогично, предлагаю везде избавиться от избыточного `else`

2024-03-29 19:45 UTC, IvanPeleshok approved these changes
Поздравляю, работа принята
Отлично потрудились

Оставил небольшие комментарии по улучшению кода

Хорошего дня

2024-03-29 19:45 UTC, IvanPeleshok commented on packages/client/src/components/exit-button/exit-button.tsx
> +    if (result?.isOk) {
```
if (!result?.isOk) {
  handleOpenPopup();
  return;
}
    
dispatch(deleteCurrentUser());
deleteAuth?.();
navigate('/login');

2024-03-29 19:45 UTC, IvanPeleshok commented on packages/client/src/providers/auth-provider.tsx
> +      const fetchUser = async () => {
Было бы замечательно вынести на уровень createAsyncThunk

2024-03-31 07:39 UTC, merged