CAT-30 | [Добавить Service Workers]
VicDoom/cat-pairs pull request #30
Opened 2024-03-28 19:12 UTC by VicDoom

### Какую задачу решаем

1. Добавлен SW для кэширования статики и запросов по принципу "Network first"

### TBD (если есть)

1. Возможно улучшение алгоритма для кэширования статики.

2024-03-29 16:26 UTC, grozzzny requested changes
В задании сказано:

> Приложение должно попадать в кеш при первой загрузке и после этого загружаться без интернета — не только элементы входа и пользовательские настройки, но и сама игра. 
> 
> Допускается использование плагинов для создания конфигурации воркера, но сам функционал требуется написать самостоятельно в соответствии с материалами из уроков.

Считаю что задача не выполнена. Исходя из первого модуля, можно было бы выложить приложение на netlify.com. Добавить sw.js в сборку проекта и закешировать основной скомпилированный js, css модули вместе с index.html. Тогда на выходе мы бы получили почти полностью автономное приложение. 

Было бы неплохо использовать консоль для дебагинга Service workers

Видео пример:

https://github.com/VicDoom/cat-pairs/assets/19452327/76a850a1-cc86-4245-a92f-28eebfe992c7

2024-03-29 16:26 UTC, grozzzny commented on packages/client/sw.js
> +        cache.put(event.request, response.clone());
cache.put это асинхронная функция. Возможно нужно добавить ожидание. await

2024-03-29 16:26 UTC, grozzzny commented on packages/client/src/helpers/service-worker-helper.ts
> +        .register('/sw.js')
sw.js успешно регистрируется. Все ок

2024-03-30 00:10 UTC, VicDoom commented
@grozzzny добавил исправление, посмотри пожалуйста - сейчас кэшируется все + можно перезагружать без интернета (иногда падает время от времени, но нечастно)

2024-03-30 00:27 UTC, grozzzny approved these changes
После перезагрузки, приложение работает!
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/116bf896-04ab-4f75-9027-576089ad772f)

2024-03-30 00:27 UTC, grozzzny commented on packages/client/src/components/game/game-logic/game-logic.tsx
> +        `public/images/cards/${this.cardBackImageName}`
😍

2024-03-30 00:27 UTC, grozzzny commented on packages/client/src/components/page-wrapper/page-wrapper.tsx
> +        src='/public/cat-background.png'
👍

2024-03-30 00:27 UTC, grozzzny commented on packages/client/src/services/auth.ts
> +      if (response?.ok && !isRequestError(response.status)) {
Отлично, что подправил

2024-03-30 05:48 UTC, IvanPeleshok requested changes
Отличная потрудились!

Есть небольшой вопрос по улучшению хелпера запросов

Хорошего дня :)

2024-03-30 05:48 UTC, IvanPeleshok commented on packages/client/src/helpers/service-worker-helper.ts
> +        .then(registration => {
Предлагаю выбирать один подход для работы с промиссами, так код будет более унифицирован
try / catch + async / await отличный сахар для работы с ними, читается куда лучше, чем колбеки

2024-03-30 05:48 UTC, IvanPeleshok commented on packages/client/src/helpers/fetch-helper.ts
> +  try {
Отлично, что позаботились об исключениях

Есть сомнения, что так и было ранее задумано
Всё-таки нам необходимо получать исключения в запросах, чтобы отображать, к примеру, информационные сообщения 
А таким образом, мы никогда не получим reject, т.к в catch не пробрасываем исключение

2024-03-30 13:49 UTC, VicDoom commented on packages/client/src/helpers/service-worker-helper.ts
> +        .then(registration => {
да, заменил на ваш вариант

2024-03-30 13:50 UTC, VicDoom commented on packages/client/src/helpers/fetch-helper.ts
> +  try {
перепроверил, все-таки лучше проверять исключения на уровне выше: показывать уведомления или просто отображать ошибки в консоли - тут просто отправка запроса; исправил

2024-03-30 21:00 UTC, nsinetskiy approved these changes
Всё отлично работает оффлайн.

2024-03-31 09:33 UTC, IvanPeleshok approved these changes
Отличная работа
Апрув
Хорошего дня :)

2024-03-31 14:19 UTC, merged