CAT-56 | [Эмодзи (бэкенд)]
VicDoom/cat-pairs pull request #61
Opened 2024-05-11 14:08 UTC by VicDoom

### Какую задачу решаем

1. Добавление бэкенда для добавления/удаления эмодзи, для получения списка реакций к комментарию
2. Были добавлены таблицы Emoji и CommentEmojiUserXRef (для реализации связи "Многие-ко-многим"), см. скрин 1
3. Были добавлены следующие ручки:

- GET /reaction/:id
- POST /reaction
- DELETE /reaction

### Скриншоты/видяшка (если есть)

![image](https://github.com/VicDoom/cat-pairs/assets/55551616/c4b77ec5-dc0a-48e5-9d5c-3aa4201f871f)

// Добавление реакции

<img width="996" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/55551616/181d493f-75d2-4037-af12-11371dfa8d70">

// Удаление реакции

<img width="998" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/55551616/006400bf-d9b3-4e6d-968c-29cb349998de">

// Получение списка реакций

<img width="1001" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/55551616/fe7b135b-ed8d-4800-9939-b9723688f175">

### TDB
1. Объединение фронта и бэкенда будет в отдельной задаче

2024-05-11 16:38 UTC, grozzzny approved these changes
Не хватает записей в таблице эмодзи. Для их добавления было бы неплохо добавить миграцию. 

npm install sequelize sequelize-cli --save-dev
npx sequelize migration:generate --name add_migrations
npx sequelize db:migrate

В целом все отлично! Approve

2024-05-11 16:38 UTC, grozzzny commented on packages/server/controllers/commentsController.ts
> +      const { commentId, emojiId } = req.body;
Если передать не существующие идентификаторы, то выпадает ошибка связанная с ForeignKey, что вводит в некое недопонимание. Было бы идеально сделать проверку о наличии комментария и emoji в БД. В случае отсутствия, выдать ошибку "комментария не существует" или "emoji не существует".  

<img width="904" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/735a7d8c-228c-43b1-9f36-a30f558862cf">

(Необязательно)

2024-05-11 16:38 UTC, grozzzny commented on packages/server/controllers/commentsController.ts
> +      const reaction = await CommentEmojiUserXRef.destroy({
Удалять реакцию можно передавая идентификатор реакции. Возможно так будет проще?

2024-05-11 16:38 UTC, grozzzny commented on packages/server/controllers/commentsController.ts
> +      return res.json(reaction);
Результат будет идентификатор реакции. Он нужен? Может нужно задать определенный формат json? 

(необязательно)

2024-05-12 15:16 UTC, grozzzny reviewed
Миграция не проходила до тех пор, пока в модели не убрал timestamp

<img width="1072" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/0693f801-98af-4c26-bc62-6aedd796bbc0">

```
@Table({
  timestamps: false,
  tableName: 'emoji',
  modelName: 'Emoji',
})
```

Поставлю approve, когда у других проверящюих после выполнения команды создадутся записи в таблице
npx sequelize db:migrate

2024-05-12 15:16 UTC, grozzzny commented on packages/server/.sequelizerc
> +  'config': path.resolve('.', 'config.json'),
Здесь нужно использовать env переменные

2024-05-12 15:16 UTC, grozzzny commented on packages/server/config.json
> +    "username": "postgres",
Этот файл не обязателен если env

2024-05-12 15:16 UTC, grozzzny commented on packages/server/models/index.js
> +import { readdirSync } from 'fs';
index.js не увидел зачем он нужен. Только ошибку выдавал при запуске проекта. удалил. все ок

2024-05-12 15:16 UTC, grozzzny commented on packages/server/migrations/add-emoji.js
> +            id: 1,
ID обычно не задают.  Они автоинкрементятся. 
<img width="351" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/5ea9ec0d-6e01-4c53-ae35-ed2407d757c0">

2024-05-12 22:56 UTC, VicDoom commented on packages/server/.sequelizerc
> +  'config': path.resolve('.', 'config.json'),
скорее всего здесь подойдет __dirname, добавил его

2024-05-12 22:56 UTC, VicDoom commented on packages/server/config.json
> +    "username": "postgres",
если его удалить, то невозможно создавать миграции, без него ругается

2024-05-12 22:56 UTC, VicDoom commented on packages/server/models/index.js
> +import { readdirSync } from 'fs';
создался автоматически, думал, он нужен для запуска

удалил

2024-05-12 22:56 UTC, VicDoom commented on packages/server/migrations/add-emoji.js
> +            id: 1,
удалил AutoIncrement, здесь его стоит задавать вручную для удобства

2024-05-13 00:02 UTC, grozzzny requested changes
Предположим, если отправить это подключение, то как будет работать проект, когда он будет развернут в продакшене с запороленной БД? Или в продакшене не нужны миграции?

Approve не может быть. Разработчик не имеет права отправлять доступы к БД в GIT.  Это грубейшая ошибка! Тут два варианта. Либо файл config.json исключить из гита, но тогда его нужно будет пробрасывать через контейнер в докере. Либо, Использовать динамическую конфигурацию, как указано в спецификации. 

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/df11720a-b589-42dd-88a4-e08d0c5d77cd)

Для меня предпочтительный вариант это ENV переменные:

<img width="542" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/afe1a425-c35f-497d-afcb-3bcd3a8134b1">

<img width="504" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/9aea6b6c-fd23-46fe-9fbe-acb40f131cfb">

2024-05-13 00:05 UTC, grozzzny commented on packages/server/migrations/add-emoji.js
> +            id: 1,
Так никто обычно не делает. Считается плохой тон, если разработчику понадобились свои идентификаторы. К тому же. autoincrement следит за уникальностью. Если нужны свои идентификаторы, то лучше использовать отдельное поле.

2024-05-13 10:56 UTC, grozzzny approved these changes

2024-05-13 10:56 UTC, grozzzny commented on package.json
> +    "migrate-db": "lerna run migrate --scope=server",
отлично

2024-05-13 10:56 UTC, grozzzny commented on .env.sample
> +POSTGRES_DIALECT=postgres
диалект было не обязательно) sequeliz это orm, которая может работать с разными базами. но так как мы выбрали postgres, то мы не будем задавать другое значение. Эта ENV может только запутать других членов команды

2024-05-13 14:36 UTC, nsinetskiy approved these changes
Миграция выполняется, запросы отправляются, ручки работают.
![image](https://github.com/VicDoom/cat-pairs/assets/10059268/0e6c7dd5-cbb5-4ddc-91af-cfaa01f3d0c4)
Добавление реакции
![image](https://github.com/VicDoom/cat-pairs/assets/10059268/d470e33e-cbd7-4516-be9a-e1cd9ec64a5d)
Получение реакций
![image](https://github.com/VicDoom/cat-pairs/assets/10059268/8b6da043-a7dd-499e-ae27-5fe404724693)
Удаление реакции
По коду замечаний нет. Отличная работа, аппрув!

2024-05-13 17:55 UTC, merged