CAT-58 [Поддержать API форума на клиенте]
VicDoom/cat-pairs pull request #64
Opened 2024-05-12 14:21 UTC by nsinetskiy

### Какую задачу решаем
Что ожидается:

В проекте полностью реализована функциональность форума. Клиент может: 

- посмотреть все топики, 

- создать новый топик, 

- написать комментарий. 

Все изменения сохраняются в базу данных и доступны после перезагрузки страницы

Пояснение:

Подключение API форума к UI, реализованному в пятом спринте.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-05-12 15:32 UTC, VicDoom commented on packages/client/src/components/forum-topic-feed-item/forum-topic-feed-item.tsx
> +// import { ForumTopicComment } from '@/helpers/types';
закомментированные строки можно удалить (здесь и далее по коду)

2024-05-12 15:32 UTC, VicDoom commented on packages/client/src/components/forum-topics-list/forum-topics-list.tsx
> +        .then(data => redirectToUrl(`/forum/${data.id}`))
navigate в этом случае не подойдет?

2024-05-12 15:32 UTC, VicDoom commented on packages/client/src/helpers/time-format-converter.ts
> +      const formatter = new Intl.DateTimeFormat('ru-RU', {
хорошо, что используешь расширенные  возможности js (Intl)

2024-05-12 21:13 UTC, Partisanov approved these changes
https://github.com/VicDoom/cat-pairs/assets/56271812/7690635d-4416-466b-b0fb-d43375147a4c
Контейнеры собираются без ошибок, темы создаются, сообщения добавляются, после выхода из игры, всё сохраняется
По коду рекомендую убрать комментарии

Аппрув

2024-05-12 21:59 UTC, VicDoom commented
Топики/комментарии создаются. Информация (текст/дата создания) отображаются. В качестве улучшения предлагаю:

- посмотреть замечания по коду, они совсем незначительные
- добавить отображения пользователя, который создал комментарий к топику

Хорошая работа, аппрув)

![image](https://github.com/VicDoom/cat-pairs/assets/55551616/6c8453ba-cc4f-431c-aa27-94063dd1d532)

2024-05-12 22:00 UTC, VicDoom approved these changes

2024-05-13 01:33 UTC, grozzzny approved these changes
Все ок! А по поводу имени комментатора, то я написал как это можно сделать. всего две строчки кода на сервере

2024-05-13 01:33 UTC, grozzzny commented on packages/client/src/components/forum-topic/forum-topic.tsx
> +              // name={item.name}
Чтобы в объекте добавить данные о пользователе, их нужно возвращать с сервера. 

 При получении темы с комментариями:
<img width="795" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/c4e36ebb-df71-473d-8c94-6b609cda902a">

При добавлении комментария (Можно вставить данные webUser они чуть меньше чем у юзера, но структура такая же. Для имени хватит):
<img width="601" alt="image" src="https://github.com/VicDoom/cat-pairs/assets/19452327/e2d83513-f369-4ffd-98d9-82028b425f7d">

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/aa36b4d8-673a-4567-ac2b-ddb087494d4f)

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/bb37cc43-bd37-4faf-81ee-a94c03e22e6f)

2024-05-13 01:33 UTC, grozzzny commented on packages/client/src/components/forum-topic-feed-item/forum-topic-feed-item.tsx
> +  // name: string;
Ниже написал как добавить данные сервера. Там всего две строчки

2024-05-13 01:33 UTC, grozzzny commented on packages/client/src/components/forum-topic/forum-topic.tsx
>                text={item.text}
проверил на XSS
```
<img src="/404-or-trash-url.png" onerror="alert('XSS')">
```
Все ок. Нет проблем

2024-05-13 01:33 UTC, grozzzny commented on packages/client/src/components/forum-topics-list/forum-topics-list.tsx
> +        .then(data => redirectToUrl(`/forum/${data.id}`))
Да. Соглашусь с Никитой. Тут лучше navigate

2024-05-13 01:33 UTC, grozzzny commented on packages/client/src/pages/forum-page/forum-page.tsx
> +    return () => service.api.abortController.abort();
Отлично, что используешь прерывание

2024-05-13 01:33 UTC, grozzzny commented on packages/server/middleware/Validator.ts
> -    userId: Joi.number().required(),
Отлично, что исключил идентификатор юзера, оставляющего комментарий. Теперь никто не скомпроментирует данные

2024-05-13 08:19 UTC, kate-lozovaya commented
Привет!
Сейчас у ветки есть конфликт. Реши его, пожалуйста, и призывай меня к ревью

2024-05-13 09:37 UTC, nsinetskiy commented
> Привет! Сейчас у ветки есть конфликт. Реши его, пожалуйста, и призывай меня к ревью

@kate-lozovaya Привет! Конфликты разрешил, отправил на повторную проверку.

2024-05-13 15:18 UTC, kate-lozovaya requested changes
Оставила несколько комментариев. Поправь код по ним и по комментариям коллег и призывай меня к ревью

2024-05-13 15:18 UTC, kate-lozovaya commented on packages/client/src/components/forum-topic-feed-item/forum-topic-feed-item.tsx
> +  createdAt: string | undefined;
[Вопрос]
Тут важно показать, что поле createdAt обязательно есть? Может сделать просто `createdAt?: string;`

2024-05-13 15:18 UTC, kate-lozovaya commented on packages/client/src/components/forum-topic-feed-item/forum-topic-feed-item.tsx
> +      <div className='forum-topic-feed-item__time'>{createdAt}</div>
[Исправление]
Не нужно отображать `createdAt`, если он `undefined`

2024-05-13 15:18 UTC, kate-lozovaya commented on packages/client/src/components/forum-topic/forum-topic.tsx
> +  };
[Исправление]
Оберни в useCallback, чтобы функция не пересоздавалась на ререндеры

2024-05-13 15:18 UTC, kate-lozovaya commented on packages/client/src/components/forum-topics-list/forum-topics-list.tsx
> +    const createNewTopic = async () => {
[Исправление]
Оберни функцию в useCallback, чтобы она не пересоздавалась на ререндеры

2024-05-13 15:18 UTC, kate-lozovaya commented on packages/client/src/helpers/time-format-converter.ts
> +  if (timeString) {
[Предложение]
Мне больше нравится делать сразу выход из функции, если условие не выполнено, чтобы не было лишней вложености.
Тут можно сделать проверку
```
if (!timeString) return;
```
и тогда все тело функции будет без дополнительной табуляции

2024-05-13 15:18 UTC, kate-lozovaya commented on packages/client/src/helpers/time-format-converter.ts
> +      return time;
[Предложение]
Можно сразу сделать `return` без дополнительной переменной. Если правила линтера, которые умеют такое делать автоматически

2024-05-13 15:18 UTC, kate-lozovaya commented on packages/client/src/helpers/time-format-converter.ts
> +      return formattedDate;
[Предложение]
Можно сразу сделать `return` без дополнительной переменной

2024-05-13 15:18 UTC, kate-lozovaya commented on packages/client/src/helpers/types/forum.ts
> +  // userId: number;
[Исправление]
Убери комментарии, либо подпиши TODO, чтобы понятно было, зачем они нужны и когда их убирать

2024-05-13 19:46 UTC, nsinetskiy commented on packages/client/src/components/forum-topic/forum-topic.tsx
> +              // name={item.name}
Спасибо, получилось!

2024-05-13 20:45 UTC, nsinetskiy commented on packages/client/src/components/forum-topic-feed-item/forum-topic-feed-item.tsx
> +// import { ForumTopicComment } from '@/helpers/types';
Убрал.

2024-05-13 20:45 UTC, nsinetskiy commented on packages/client/src/components/forum-topics-list/forum-topics-list.tsx
> +        .then(data => redirectToUrl(`/forum/${data.id}`))
Убрал redirectToUrl, заменил на navigate.

2024-05-13 21:56 UTC, nsinetskiy commented on packages/client/src/components/forum-topic-feed-item/forum-topic-feed-item.tsx
> +  createdAt: string | undefined;
Поправил.

2024-05-13 21:56 UTC, nsinetskiy commented on packages/client/src/components/forum-topic-feed-item/forum-topic-feed-item.tsx
> +      <div className='forum-topic-feed-item__time'>{createdAt}</div>
Добавил проверку.

2024-05-13 21:56 UTC, nsinetskiy commented on packages/client/src/components/forum-topic/forum-topic.tsx
> +  };
Обернул.

2024-05-13 21:57 UTC, nsinetskiy commented on packages/client/src/components/forum-topics-list/forum-topics-list.tsx
> +    const createNewTopic = async () => {
Обернул.

2024-05-13 21:58 UTC, nsinetskiy commented on packages/client/src/helpers/time-format-converter.ts
> +  if (timeString) {
Добавил проверку. Стало красивее.

2024-05-13 21:58 UTC, nsinetskiy commented on packages/client/src/helpers/time-format-converter.ts
> +      return time;
Убрал переменную.

2024-05-13 21:59 UTC, nsinetskiy commented on packages/client/src/helpers/time-format-converter.ts
> +      return formattedDate;
Убрал переменную.

2024-05-13 21:59 UTC, nsinetskiy commented on packages/client/src/helpers/types/forum.ts
> +  // userId: number;
Комментарии убрал.

2024-05-13 22:04 UTC, nsinetskiy commented
> Оставила несколько комментариев. Поправь код по ним и по комментариям коллег и призывай меня к ревью
@kate-lozovaya Поправил код по всем комментариям. Отправил ссылку на новую проверку.

2024-05-14 07:28 UTC, kate-lozovaya approved these changes
Хорошая работа 👍🏻

2024-05-14 07:43 UTC, merged