Cat 25
VicDoom/cat-pairs pull request #7
Opened 2024-03-11 13:23 UTC by Partisanov

### Какую задачу решаем
Создание механики игры на Canvas API

2024-03-11 15:22 UTC, grozzzny requested changes
Изображения в public/images - это хорошо. Был разговор про картинки сгенерированные АИ, но это вообще не критично. 

Немного не понятно там где "Находим индекс карточки по координатам клика", по идее можно было бы прикрутить событие на сам элемент. Но раз сама механики игры рабочая, то скорее всего так и должно быть. 

Еще один момент. Лучше конечно разделить логику GamePage (Компоненты страницы) с компонентом самой игрой и расположить его в отдельной директории. Например game. Чтобы в дальнейшем можно было бы расширять логику и дорабатывать функционал. Но так как это учебное задание, думаю для сдачи проекта подойдет на все 100%. 

Вот на что, я бы обратил внимание:
Цифры при подсчете толкают весь контент. 
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/aa2df721-2029-4ead-ac52-bf8b27634871)

Начинать первый уровень с двух карточек это беспроигрышный вариант этого уровня. Выглядит как баг. По мне лучше начать хотя бы с 6 карточек, чтобы был интерес к  игре. 

Ну и подправить бы расположение кнопок. 
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/2bfd75b5-c7b8-4a12-8981-ed2cf3e2e3cd)

2024-03-12 18:22 UTC, VicDoom commented on packages/client/src/pages/game-page/game-page.tsx
> +  const [selectedDifficulty, setSelectedDifficulty] = useState<string>('easy');
предлагаю вынести типы уровней (простой/сложный) и статус игры в enum

2024-03-12 18:25 UTC, VicDoom commented on packages/client/src/pages/game-page/game-page.tsx
> +    if (!ctx) return;
давай для чистоты кода сократим 136 и 138 строки в один return

2024-03-12 18:29 UTC, VicDoom commented on packages/client/src/pages/game-page/game-page.tsx
> +                alignItems: 'end',
подскажи, здесь же можно убрать стили в отдельный css файл?

2024-03-12 18:30 UTC, VicDoom commented on packages/client/src/pages/game-page/game-page.tsx
> +              onChange={e => setSelectedDifficulty(e.target.value)}>
не хватает переноса строки

2024-03-12 18:33 UTC, VicDoom commented on packages/client/src/pages/game-page/game-page.tsx
> +    const size = level * 2;
по коду часто встречается 2, как количество карточек для фиксации, можно вынести в константу CARD_NUMBER_TO_FIXATE или аналогичное название

2024-03-12 18:40 UTC, VicDoom commented
Очень хорошая реализация, лично мне нравится, осталось несколько спорных моментов:

1. Поле с карточками дергается из-за цифр (Дима на это уже указал, но это критичный момент, можно пока что игру сделать под таймером, чтобы решить проблему)
2. Можно расположить игру по центру
3. Предлагаю все же придерживаться сложности, которую заранее обговорили и зафиксировали (см. тред в пачке).
4. Посмотри, пожалуйста, замечания по код-стайлу. Их немного и они мелкие, но нужно исправить

Остальные шероховатости игры можно будет поправить позже. И дополнительные анимации скорее всего тоже

2024-03-13 00:37 UTC, Partisanov commented
Пофиксил недочеты, 
добавил 2 компонента Левел и Таймер, вынес стили в отдельные файлы, 
 добавил масштабирование карточек когда и много, 
изменил логику отрисовки карточек, количество карточек на доске в зависимости  уровня:
1 уровень : 3х2, 
2 уровень : 4х4, 
3 уровень : 6х6,
4 уровень и далее: 8х8 , 
и начиная с 5го от времени отнимается 10 сек

2024-03-13 08:06 UTC, grozzzny approved these changes
Добавил enum, и вывел стили в отдельный класс. Хорошо!

Немного смутил таймер на 500. Но думаю это никак не заметно.

2024-03-13 08:06 UTC, grozzzny commented on packages/client/src/components/timer/timer.tsx
> +      className='timer'
Хорошо, что вынес стили в отдельный класс

2024-03-13 08:06 UTC, grozzzny commented on packages/client/src/pages/game-page/game-page.tsx
> +    setGameStatus(GameStatus.WON);
enum. Отлично

2024-03-13 08:48 UTC, Partisanov commented on packages/client/src/pages/game-page/game-page.tsx
> +    const size = level * 2;
add const PAIR_CARDS

2024-03-13 09:11 UTC, VicDoom commented
Прототип отличный, мне нравится, что можно поправить:

1. Сделать начальным уровнем 1й уровень
2. Пофиксить баг, связанный с мерцанием карточек (клик на карточку провоцирует моргание всех карточек на поле)

2024-03-13 09:25 UTC, Partisanov commented
@VicDoom , по пункту 1) Игра начинается с 1 уровня, скорее всего у тебя в локалсторидж с прошлой игры , тк сейчас у нас не подтягивается левел игрока, я сохраняю его в локалсторидж, для того чтобы при перегрузке страницы не терялся прогресс в игре :) 
по 2 пункту ) Да я тоже вижу эту проблему, но решения пока не нашел, если кто знает как победить, буду признателен

2024-03-13 12:29 UTC, VicDoom approved these changes

2024-03-13 16:19 UTC, kyzinatra commented on packages/client/src/components/level/level.tsx
> +
Можно лучше: как насчет того, чтобы использовать `css` модули? Они более гибкиеза счет того,  что стили не попадают вглобальную область видимости

2024-03-13 16:19 UTC, kyzinatra commented on packages/client/src/components/timer/timer.tsx
> +    '0'
Можно лучше: форматирование времени лучше вынести отдельно

2024-03-13 16:20 UTC, kyzinatra commented on packages/client/src/components/timer/timer.tsx
> +  const formatTime = `${String(Math.floor(time / 60)).padStart(
Можно лучше: а что если `color == undefined`, тогда цвет будет не валидным

2024-03-13 16:21 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
>  };
Компонент получилсяочень большой, стоит его  разбить на несколько более мелких

2024-03-13 16:22 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +  const [timeLeft, setTimeLeft] = useState<number>(0);
Можно лучше: если тип можно вывести из аргумента, то его можно не вводить  руками, `ts` сделает это сам

2024-03-13 16:23 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +  >([]);
Можно лучше: такие большие типы лучше вынести отдельно

2024-03-13 16:23 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +    [THEME]
Можно лучше: выполнение такого простого условия очень быстрая операция и она не требует мемоизации. Даже наоборот. мемоизация тут вредит

2024-03-13 16:24 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +    while (rows > columns) {
Можно лучше: математику лучше  вынести отдельно

2024-03-13 16:27 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +      initGame();
Мне  кажется, что вместо `useEffect`  вызывать эту функцию можно прямо там, где мы запускаем игру. Будет короче и мы не будет лишний раз использовать  `useEffect`. Подробнее https://youtu.be/_NV5DxUcyGM?si=18lQLwNrBXy-BewS

2024-03-13 16:29 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +    1: 3,
Если это константа, то тип можно задать как `as const`

2024-03-13 16:30 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +          10 * (level - 4);
Можно записать короче: `countCards * (selectedDifficulty === Difficulty.EASY ? 4 : 3) - 10 * ((level - 4) || 1)`

2024-03-13 16:31 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +      const j = Math.floor(Math.random() * (i + 1));
Тоже можно вынести как утилитарную функцию

2024-03-13 16:33 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +    ctx.arcTo(x, y, x + width, y, radius);
Рисовка тоже не должна быть частью компоненте. Вы можете использовать классы, чтобы организовать рендер canvas в стиле ООП, или функциональный подход. Но в любом случае в компонент мы должны  получать только внешний API, куда бы передавали условно `.startGame()`, `.endGame()`, `.onLoose()` итп, а остальное бы делал класс или функция, которая не находится в этом компоненте

2024-03-13 16:37 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +      ctx.save();
Проблема с мельканием катрочек вот тут.  Если вы посмотритена скрин то увидите запросы к серверу. Сначала их много, потому что сайт грузится, а потом он на каждую прорисовку новой карточки (в том числе и повторную) посылает новый запрос к серверу. Что, конечно, очень долго. Чтобы не было моргания картинки нужно кэшировать

2024-03-13 16:43 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +    img.onload = () => {
Проблема с мельканием карточек вот тут. Если вы посмотрите на скрин то увидите запросы к серверу. Сначала их много, потому что сайт грузится, а потом он на каждую прорисовку новой карточки (в том числе и повторную) посылает новый запрос к серверу. Что, конечно, очень долго. Чтобы не было моргания картинки нужно кэшировать. Также проблема может быть в долгой  загрузке и преобразованию в `Image`. Декодирование может быть затратным процессом. Если дело в этом, то можно мемоизировать `Image()`  с картинками, а  в нужный момент их отрисовывать
![image](https://github.com/VicDoom/cat-pairs/assets/51288221/e3a0f788-56d0-4cf5-a0db-ffa96821c9b7)

2024-03-13 16:43 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +    if (clickDisabled || paused) return;
Хорошая типизация событий

2024-03-13 16:44 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +            const [firstCard, secondCard] = flippedCards;
А зачем тут `setTimeout`?

2024-03-13 16:48 UTC, kyzinatra commented
Вы отлично потрудились над  реализацией логики. Сейчас игра уже вполне играбельная. Но есть небольшие вопросы к коду. Писать всю логику в 1 компоненте не  стоит. Это делать его не читабельным и сложным к модификациям. Советую написать логику canvas в стиле ООП, а также разделить копомонент на несколько частей. Это критичное замечание, так как мидл разработчику очень важно писать понятный и простой  код. Если по комментариям остались вопросы, то можете меня тэгнуть @kyzinatra

2024-03-13 16:53 UTC, Partisanov commented on packages/client/src/components/level/level.tsx
> +
Обсудили с командой, мы используем БЭМ в проекте, решили модули не использовать

2024-03-13 18:51 UTC, Partisanov commented on packages/client/src/pages/game-page/game-page.tsx
> +    1: 3,
<img width="953" alt="Снимок экрана 2024-03-13 в 23 47 36" src="https://github.com/VicDoom/cat-pairs/assets/56271812/ae282fd3-4830-424d-b633-6dc9118042ec">
ts не понравился такой вариант, или я что-то не так сделал

2024-03-13 18:57 UTC, kyzinatra commented on packages/client/src/pages/game-page/game-page.tsx
> +    1: 3,
А тут уже проблема в типе level. Он number, а ts требует, чтобы он был 1 | 2 | 3, потому что только такой ключ подойдет

2024-03-18 16:58 UTC, Partisanov commented
@kyzinatra учел все недочеты, переделал

2024-03-18 20:08 UTC, kyzinatra commented
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2024-03-20 03:25 UTC, merged