Cat 23
VicDoom/cat-pairs pull request #8
Opened 2024-03-11 15:21 UTC by VoskresenskayaM

### Верстка экрана завершения игры

### https://skr.sh/vOhJG6hYWUA

### TBD (если есть)

2024-03-11 16:03 UTC, grozzzny requested changes
Иконка в директории public это хорошо. 

Не используется BEM в названиях css классов - плохо. 

Комит, именно описание его не соответствует принятому соглашению командой. Вот пример договоренности: feat(TEST-1): test commit

Также была договоренность фиксировать версии библиотек:
react-confetti@^6.1.0

Не используется var(). коды цветов должны быть выведены в общий файл

При наведении белый фон с белыми буквами. Это косвенно относится к задаче, так как кнопка используется antd, базовые цвета которых не сочетаются. По хорошему, чтобы не создавать отдельную задачу, можно подправить базовые цвета в рамкой этой. 
![image](https://github.com/VicDoom/cat-pairs/assets/19452327/5a4cd04b-3774-46e1-8b89-f1889696b080)

![image](https://github.com/VicDoom/cat-pairs/assets/19452327/e725fdf1-94a7-4100-b053-d91d5e1b06a3)
Надпись "выход из игры", не является кнопкой, что вводит заблуждение в поиске области кликабельности. 

В целом норм. только вот что с BEM делать? Думаю пусть Никита решает.

2024-03-11 16:03 UTC, grozzzny commented on yarn.lock
> +react-confetti@^6.1.0:
была договоренность фиксировать версии библиотек

2024-03-11 16:03 UTC, grozzzny commented on packages/client/src/pages/gameover-page/gameover-page.css
> +  background-color: #565a5d;
не используется var(). коды цветов должны быть выведены в общий файл

2024-03-11 22:33 UTC, grozzzny approved these changes
отлично

2024-03-12 18:49 UTC, VicDoom commented
ВАЖНО: Маша, пожалуйста, перед мерджем смени конечную ветку на dev!

2024-03-12 19:21 UTC, VicDoom commented on packages/client/src/components/exit/exit.tsx
> +    <div className='exit__container'>
БЭМ применен неверно, сейчас exit__container, exit__link и тд являются элементами, элементы обязаны быть частью блока exit

И отсюда два момента:
1. В компоненты выносятся штуки, которые переиспользуются, вроде Exit используется в одном месте (некритично)
2. Предлагаю вместо Exit назвать компонент ExitButton и поменять нейминг стилей соответственно (exit -> exit-button)

2024-03-12 19:22 UTC, VicDoom commented on packages/client/src/components/game-over/game-over.css
>    color: #565a5d;
давай вынесем в переменную стилей и сделаем через var()

2024-03-12 19:25 UTC, VicDoom commented on packages/client/src/components/game-over/game-over.tsx
> +    <div className='gameover__container'>
давай переименуем GameOver -> GameOverWrapper (или как-то аналогично), название компонента должно немного отражать что в нем лежит - диалог, кнопка или обертка для заголовка с поздравлением)

сюда же и названия стилей - поправь пожалуйста

2024-03-12 19:27 UTC, VicDoom commented on packages/client/src/components/exit/exit.tsx
> +      <Link className='exit__link' to='/'>
Link - это хорошо, но можно еще использовать хук useNavigate, он уже использовался в проекте, он нативнее в применении (некритично)

2024-03-12 19:29 UTC, VicDoom commented on packages/client/package.json
> +    "react-confetti": "^6.1.0",
зафиксируй версию (убери флажок)

2024-03-12 19:36 UTC, VicDoom commented on packages/client/src/pages/gameover-page/gameover-page.tsx
> +        <Exit />
![image](https://github.com/VicDoom/cat-pairs/assets/55551616/28ac2354-3c73-49d2-8dcb-430fcefa3048)

имхо, но лучше кнопку выхода игры так сильно не прятать, можно расположить ее под кнопкой продолжить игру и чуть-чуть увеличить шрифт

ИЛИ

просто увеличить ей шрифт

2024-03-12 23:14 UTC, VicDoom commented on packages/client/src/components/game-over/game-over.css
> +  display: flex;
еще один совет, в antd есть компонент Flex, который позволяет выравнивать содержимое по твоему усмотрению, это очищает css код от повторяющихся настроек флексов:

https://ant.design/components/flex

2024-03-14 22:03 UTC, VicDoom commented on packages/client/src/components/exit-button/exit-button.tsx
> +      <button className='exit-button__button'>
exit-button__wrapper

2024-03-14 22:03 UTC, VicDoom commented on packages/client/src/components/exit-button/exit-button.tsx
> +        <p className='exit-button__button-text'>выход из игры</p>
exit-button__text

2024-03-14 22:05 UTC, VicDoom commented on packages/client/src/components/exit-button/exit-button.css
> +  background-color: #efe5cc;
> var(--light)

2024-03-14 22:06 UTC, VicDoom commented on packages/client/src/components/game-over-wrapper/game-over-wrapper.css
>    color: #efe5cc;
> var(--light)

2024-03-14 22:13 UTC, VicDoom commented on packages/client/src/components/exit-button/exit-button.tsx
> +export const ExitButtom = () => {
ExitButtom -> ExitButto**n**

2024-03-14 22:21 UTC, VicDoom commented on packages/client/src/pages/gameover-page/gameover-page.tsx
> +        <Exit />
Кнопка стала побольше, теперь ее лучше видно!

2024-03-15 15:09 UTC, grozzzny requested changes
Только кнопку подтянуть, чтобы уже не возвращаться к этой задаче. А так, мне нравится как сделано. Креативно!

2024-03-15 15:09 UTC, grozzzny commented on packages/client/src/components/exit-button/exit-button.tsx
> +      <button className='exit-button__button'>
Подтянешь кнопку? Скоро компонент будет в деве. дам знать.

2024-03-18 09:33 UTC, grozzzny approved these changes
Отлично.

2024-03-18 18:11 UTC, VicDoom commented on packages/client/src/components/game-over-wrapper/game-over-wrapper.tsx
> +import { Button } from '@/components/button';
можно сократить импорт (опционально)

2024-03-18 18:12 UTC, VicDoom approved these changes

2024-03-18 19:13 UTC, merged